[app]
name = "backend-ecommerce"
port = 8080
env = "development"

[database]
host = "localhost"
port = 3306
user = "root"
password = "root"
name = "backend-ecommerce"
charset = "utf8mb4"
parse_time = true
loc = "Local"
timeout = "10s"

[redis]
host = "localhost"
port = 6379
password = ""
db = 0

[jwt]
secret_key = "your-secret-key-here"
access_token_expiry = "15m"
refresh_token_expiry = "24h"